security:
    resource: "@AppSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

ebooks:
    resource: "@EbooksBundle/Controller/"
    type:     annotation
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

logout:
    path: /logout
